repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: "isort (python)"
    types: [python]
    args: [--add-import, from __future__ import annotations]

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.982
  hooks:
  - id: mypy
    args: [--strict]

- repo: https://github.com/pycqa/pylint
  rev: v2.15.5
  hooks:
  - id: pylint
