name: Run ssh_to_pipeline.py
on: []
jobs:
  run-ssh-to-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run ssh_to_pipeline.py
        run: |
          python3 ${{ github.workspace }}/ssh_to_pipeline.py
